appsetup/urls.py
"""
Definition of urls for setup.
This mostly ties urls to methods in views.py
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views


# variables inherited from django, replaced string value
# handler404 = 'app.views.error_handler_404'
# handler500 = 'app.views.error_handler_500'

# set the urls to views & gives them a name
# example : path('about/', views.about, name='about')
#  1st part (ex: "about/") is url part
#  2nd part (ex: views.about) is method that controls how page looks like the page looks
#  name part allows references to it (ex: name="about" allows href="{% url 'about' %}")
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('admin_settings/', views.admin_settings, name="admin_settings"),
    path('history/', views.history, name="history"),
    path('people/', views.people, name="people"),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('accounts/register/', views.register_view, name="signup"),

    path('user/password/', views.change_password, name='change_password'),
    path('user/profile/', views.profile, name ="profile"),
    path('user/settings/', views.user_settings, name="user_settings"),


    path('inventory/', views.InventoryIndex.as_view(), name='inventory_index'),
    path('inventory/<slug:search>', views.InventoryIndex.as_view(), name='inventory_index_searched'),
    path('inventory/items/<int:page>', views.items, name='items'),
    path('inventory/items/<int:page>/<slug:searchby>/<slug:searched>', views.items, name='items_searched'),
    path('inventory/create_item/', views.ItemCreateView.as_view(), name='create_item'),
    path('inventory/update_item/<int:pk>', views.ItemUpdateView.as_view(), name='update_item'),
    path('inventory/read_item/<int:pk>', views.ItemReadView.as_view(), name='read_item'),
    path('inventory/delete_item/<int:pk>', views.ItemDeleteView.as_view(), name='delete_item'),
    path('inventory/read_vendor/<int:pk>/', views.ReadVendor.as_view(), name='ReadVendor'),

    path('vendors/<int:item>/', views.VendorIndex.as_view(), name='VendorList'),
    path('vendors/<int:item>/delete_item/<int:pk>/', views.VendorDeleteView.as_view(), name='delete_vendor'),
    path('vendors/<int:item>/create_item/', views.VendorCreateView.as_view(), name='create_vendor'),
    path('vendors/<int:item>/update_item/<int:pk>/', views.VendorUpdateView.as_view(), name='update_vendor'),
    path('vendors/<int:itemfk>', views.vendors, name='vendorslist'),

    path('users/', views.PeopleIndex.as_view(), name="people_index"),
    path('users/<slug:search>', views.PeopleIndex.as_view(), name='people_index_searched'),
    path('users/update_user/<int:pk>', views.UserUpdateView.as_view(), name='update_user'),
    path('users/delete_user/<int:pk>', views.UserDeleteView.as_view(), name='delete_user'),
    path('users/people/', views.users_list, name="user_list"),

]

app/models.py
"""
Definition of models.
"""

# from xmlrpc.client import DateTime
# from django import db
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser # , User
# from django_boost.models.fields import AutoOneToOneField
from django.utils.timezone import now
from annoying.fields import AutoOneToOneField
from django.contrib.auth.models import Group

# Create your models here.
# created a table for admin settings
# print(now())

RANK_CHOICES = (
    ('Admin', 'Admin'),
    ('Manager', 'Manager'),
    ('Viewer', 'Viewer'),
)
RANK_GROUPS = ["Admin", "Manager", "Viewer"]
class CustomUser(AbstractUser):
    rank = models.CharField(max_length=10,choices=RANK_CHOICES,default="Viewer")

    def save(self, *args, **kwargs):
        # remove user from rank groups
        query_set = Group.objects.filter(user = self.pk)
        for g in query_set:
            if g.name in RANK_GROUPS:
                g.user_set.remove(self)
                # self.user.groups.remove(group)

        # assign user to new rank group
        if self.rank == "Admin":
            group, created = Group.objects.get_or_create(name='Admin')
        elif self.rank == "Manager":
            group, created = Group.objects.get_or_create(name='Manager')
        elif self.rank == "Viewer":
            group, created = Group.objects.get_or_create(name='Viewer')
        group.user_set.add(self.pk)
        super(CustomUser, self).save(*args, **kwargs)



User = get_user_model()

class recent_alerts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=45)
    
    class Meta:

        db_table="recent_alerts"

#new history page
class recent_new_user(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    descrption = models.CharField(max_length=250)
    created_date = models.DateTimeField(default=now, editable=False)

    class Meta:
        
        db_table="recent_new_user"

class recent_new_item(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    description = models.CharField(max_length=45)
    newItem = models.CharField(max_length=45)

    class Meta:

        db_table = "recent_new_item"

# Mockup purchase history db. Inactive, need to create db in Heroku. -Thomas
class purchase_history(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    descrption = models.CharField(max_length=45)
    # add time attribute to this and other audit logs?

    class Meta:

        db_table="purchase_history"

# Mockup inventory changes db. Inactive, need to create db in Heroku. -Thomas
class inventory_changes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    descrption = models.CharField(max_length=45)
    # add time attribute to this and other audit logs?

    class Meta:

        db_table="inventory_changes"

class history(models.Model):
    id = models.IntegerField(primary_key= True)
    description = models.CharField(max_length=100)
    time = models.DateField()

    class Meta:
        db_table = "history"
       

# for settings, left is value right is appearance
FONT_CHOICES = (
    ('Arial', 'Arial'),
    ('Courier New', 'Courier'),
    ('Times New Roman', 'Times New Roman'),
    ('Verdana', 'Verdana'),
)
PAGINATE_BY_CHOICES = (
    (5, '5'),
    (10, '10'),
    (15, '15'),
    (25, '25'),
    (50, '50'),
    (100, '100'),
    (0, 'All')
)
class personal_user_settings(models.Model):
    user = AutoOneToOneField(to=User, on_delete=models.CASCADE, primary_key=True, related_name="user_profile")
    font_type = models.CharField(max_length=20, choices=FONT_CHOICES, default='Arial')
    paging_by = models.PositiveSmallIntegerField(choices=PAGINATE_BY_CHOICES, default=10)

    class Meta:
        db_table = "personal_user_settings"

class global_settings(models.Model):

    allow_inventory_changes = models.BooleanField(default=False)
    allow_adding_new_users = models.BooleanField(default=False)
    allow_inventory_purchases = models.BooleanField(default=False)
    allow_paring_data = models.BooleanField(default=False)

    class Meta:
        db_table = "global_settings"

class Item(models.Model):

    title = models.CharField(max_length=50)
    alert = models.BooleanField(default = True)
    image_path = models.CharField(max_length = 500, blank=True)
    stock = models.PositiveIntegerField(default=0)
    threshold = models.PositiveIntegerField(default=1)
    part_number = models.CharField(max_length = 15, blank=True)

    def save(self, *args, **kwargs):
        if self.stock > self.threshold:
            self.alert = False
        else:
            self.alert = True
        super(Item, self).save(*args, **kwargs)


class Vendor(models.Model):
    path = models.URLField(max_length=500)   
    name = models.CharField(max_length=100)
    itemfk = models.ForeignKey(Item, unique=False, on_delete=models.CASCADE)
    
# Temporary, deprecates when File Upload is ready.
class mock_inventory(models.Model):
    item = models.IntegerField(primary_key = True)
    alert = models.BooleanField(default = True)
    name = models.CharField(max_length = 100)
    image = models.CharField(max_length = 500)
    amount = models.IntegerField()
    description = models.CharField(max_length = 500)

    class Meta:
        db_table = "mock_inventory"

app/templates/app/people/index.html
{% extends 'app/layout.html' %}

{% block content %}
<head>    
  <title>Users</title>
<!--    <link rel="stylesheet" type="text/css" href="css/style2.css">-->
  {% load static %}
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'app/content/style.css' %}" /> -->
  <style>
		h2{
   			 text-align: center;
   			 color: #000000;
  			  padding: 20px;
   			 text-decoration: overline underline;
		}

		h3{
            text-align: center;
            text-decoration: underline;
        }

    .nostretch{
        width: 100px !important; 
      }
        
	</style>
</head>   


  <br><br>
  <!-- <h2 style="text-decoration: underline overline;">Inventory</h2><br> -->
  <div class="container mt-5 mb-5"></div>
    <h1 class="modal-title text-center">Users</h1>
  </div>

  
  <div>
    {% if perms.app.add_customuser %}
      <a href="{% url 'signup' %}">
        <button type="button" class="btn btn-primary" id="add_user_button" style="margin:0 auto; display:block;" >Add New User </button>
      </a>
      <br>
    {% endif %}
    </div>  
  {% include "app/_modal.html" %}

  <div class="scrollbar scrollbar-primary">
    <div class="force-overflow"></div>
  </div>

  <div class="container mt-3">
    
    <div class="row">
      <div class="col">
        <div class="row">
          <div class="col-12 mb-3">
          {% include "app/people/table.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block extrascripts %}
<script type="text/javascript">
  var tag = document.getElementById('searchby');
  var button = document.getElementById('editsearch');
  button.onclick = function() {
  if (tag.style.display == "block") {
    tag.style.display = "none";
  } else {
    tag.style.display = "block";
  }
}
</script>
<script type="text/javascript">
  $(function () {

      //  Signup
      // $("#signup-btn").modalForm({
      //   formURL: "{% url 'create_item' %}", // replace create_item with signupname
      // });


      // Update book asynchronous button
      // message
      var asyncSuccessMessageUpdate = [
        "<div ",
        "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
        "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
        "Success: User was updated.",
        "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
        "<span aria-hidden='true'>&times;</span>",
        "</button>",
        "</div>",
        "<script>",
        "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
        "<\/script>"
      ].join("");

      // modal form
      function updateUserModalForm() {
        $(".update-user").each(function () {
          $(this).modalForm({
            formURL: $(this).data("form-url"),
            asyncUpdate: true,
            asyncSettings: {
              closeOnSubmit: false,
              successMessage: asyncSuccessMessageUpdate,
              dataUrl: "people/",
              dataElementId: "#user-table",
              dataKey: "table",
              addModalFormFunction: reinstantiateModalForms
            }
          });
        });
      }
      updateUserModalForm();

      // Delete User buttons - formURL is retrieved from the data of the element
      function deleteUserModalForm() {
        $(".delete-user").each(function () {
            $(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
        });
      }
      deleteUserModalForm();

      function reinstantiateModalForms() {
        updateUserModalForm();
        deleteUserModalForm();
      }

      // Hide message
      $(".alert").fadeTo(2000, 500).slideUp(500, function () {
          $(".alert").slideUp(500);
      });

  
  });
</script>
<script type="text/javascript">
    $(function () {

    function toggleSearch() {
      var search_submit_var = document.getElementById("search_submit");
      if ($(this).style.display == "block") {search_submit_var.disabled=true;}
      else {search_submit_var.disabled=false;}
    }

    // Read user buttons
    function suppressSearch() {
      $("#exampleModal").each(function () {

        $(this).on('shown.bs.modal', function () {
          // will only come inside after the modal is shown/visible
          var search_submit_var = document.getElementById("search_submit");
          search_submit_var.disabled=true;
        });
        $(this).on('hidden.bs.modal', function () {
          // will only come inside after the modal is shown/visible
          var search_submit_var = document.getElementById("search_submit");
          search_submit_var.disabled=false;
        });
      });
    }
    suppressSearch();

});
</script>
{% endblock extrascripts %}

app/templates/app/people/table.html
<table id="user-table" class="table">
  
    <thead>
    <tr>
      <th class="text-center" scope="col">Rank</th>
      <th class="text-center" scope="col">Username</th>
      <th class="text-center" scope="col">First Name</th>
      <th class="text-center" scope="col">Last Name</th>
      <th class="text-center" scope="col">Email</th>
      <th class="text-center" scope="col">Last Login</th>
      <!-- <th class="text-center" scope="col">Price (€)</th> -->
      <th class="text-center" scope="col">{% if perms.app.change_customuser and perms.app.delete_customuser %} Update / Delete {% elif perms.app.change_customuser %} Update {% elif perms.app.delete_customuser %} Delete {% endif %}</th>
    </tr>
    </thead>
    <tbody>
      {% for person in persons %}
        <tr>
          <td class="text-center">{{ person.rank }}</td>
          <td class="text-center">{{ person.username }}</td>
          <td class="text-center">{{ person.first_name }}</td>
          <td class="text-center">{{ person.last_name }}</td>
          <!-- <td class="text-center">{{ item.pages }}</td> -->
          <td class="text-center">{{ person.email }}</td>
          <td class="text-center">{{ person.last_login }}</td>
        
          <td class="text-center">
              <!-- Update buttons -->
              {% if perms.app.change_customuser %}
              <button type="button" class="update-user btn btn-sm btn-primary" data-form-url="{% url 'update_user' person.pk %}">
                <span class="fa-solid fa-pencil"></span>
              </button>
              {% endif %}
              <!-- Delete buttons -->
              {% if perms.app.delete_customuser %}
              <button type="button" class="delete-user btn btn-sm btn-danger" data-form-url="{% url 'delete_user' person.pk %}">
                <span class="fa-solid fa-trash"></span>
              </button>
              {% endif %}
          
          </td>
        </tr>
      {% endfor %}
  
    </tbody>
  </table>